[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-backend"
version = "0.1.0"
description = "Federated anomaly detection backend"
license = {text = "Apache-2.0"}
dependencies = [
    "flwr[simulation]==1.27.0",
    "torch==2.11.0",
    "pandas==3.0.2",
    "numpy==2.4.4",
    "scikit-learn==1.8.0",
    "matplotlib==3.10.9",
    "transformers==5.6.2",
    "captum==0.9.0",
    "pypots>=1.4"
]

[tool.flwr.app]
publisher = "local"
name = "fl-backend"

[tool.flwr.app.components]
clientapp = "client_app:app"
serverapp = "server_app:app"

[tool.hatch.build.targets.wheel]
packages = ["data", "models", "tasks", "training","plotting"]
include = [
  "client_app.py",
  "server_app.py",
  "FedProxWithSave.py",
  "config.py",
  "main.py",
]

[[tool.uv.index]]
url = "https://pypi.org/simple"

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/rocm7.3"