[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fl-backend"
version = "0.1.0"
description = "Federated anomaly detection backend"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.20.0",
    "torch",
    "pandas",
    "numpy",
    "scikit-learn",
    "matplotlib",
]

[[tool.pip.indexes]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.3"

[tool.flwr.app]
publisher = "local"

[tool.flwr.app.components]
clientapp = "client_app:app"
serverapp = "server_app:app"


[tool.hatch.build.targets.wheel]
packages = ["data", "models", "tasks", "training"]
include = [
  "client_app.py",
  "server_app.py",
  "FedAvgWithSave.py",
  "config.py",
  "main.py",
]